### ISSUE TITLE
Support for different todo lists

### ISSUE THREAD

**Issue by Pinaki93** [Pinaki93/Check-It-Out#6]
DS:
- [ ] `TodoList`-> `id`, `listName`,`list description`,`icon`

To begin with:
- [ ] Add a default list - `My Items`
- [ ] Add existing items in the list to `default list`

UI:
- [ ] Add TodoList item
- [ ] drag to reorder
- [ ] List Screen with option to
- [ ] Name, icon, description

- [ ] Todo listing screen
- [ ] show the bottom app bar
- [ ] show menu to edit and delete the list
- [ ] Edit options -> edit name, description, item [would be a good idea to use the add todo itemscreen again]
- [ ] Add a fab to the bottom app bar to add todo item
